# Generated by Django 3.2 on 2021-04-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgboard', '0002_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('Replacement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('preparationTime', models.IntegerField()),
                ('totalTime', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('C', 'Challenging'), ('T', 'Tough')], max_length=1)),
                ('numberOfIngredients', models.IntegerField()),
                ('preparationMethod', models.CharField(choices=[('BA', 'Baking'), ('RO', 'Roasting'), ('CO', 'Cooking'), ('ST', 'Steaming'), ('FR', 'Frying'), ('PI', 'Pickling'), ('CU', 'Cuts')], max_length=2)),
                ('notes', models.TextField()),
                ('url', models.TextField()),
                ('numberOfServings', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
