# Generated by Django 2.2.10 on 2021-08-29 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('health', models.CharField(blank=True, choices=[('', ''), ('meat', 'Meat'), ('gluten-free', 'Gluten-free'), ('pecatarian', 'Pecatarian'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('kosher', 'Kosher')], max_length=20)),
                ('cuisine', models.CharField(blank=True, choices=[('', ''), ('american', 'American'), ('asian', 'Asian'), ('british', 'British'), ('chinese', 'Chinese'), ('french', 'French'), ('italian', 'Italian'), ('mediterranean', 'Mediterranean'), ('mexican', 'Mexican')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('mouths', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(blank=True, related_name='user_meals', to=settings.AUTH_USER_MODEL)),
                ('recipes', models.ManyToManyField(blank=True, related_name='meals', to='recipes.Recipe', verbose_name='Recipes')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
        ),
    ]
