# Generated by Django 2.2.10 on 2021-08-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_meals'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='meals', to='recipes.Recipe', verbose_name='Recipes'),
        ),
    ]
