# Generated by Django 2.2.10 on 2021-08-14 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField()),
                ('label', models.CharField(max_length=400)),
                ('image', models.URLField()),
                ('url', models.URLField()),
                ('yield', models.IntegerField()),
                ('calories', models.FloatField()),
                ('totalTime', models.IntegerField()),
                ('cuisineType', models.CharField(max_length=400)),
                ('mealType', models.CharField(max_length=400)),
                ('dishType', models.CharField(max_length=400)),
                ('meals', models.ManyToManyField(blank=True, related_name='recipes', to='meals.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
