# Generated by Django 2.2.10 on 2021-08-29 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('maker', models.CharField(max_length=400, null=True)),
                ('uri', models.URLField()),
                ('label', models.CharField(max_length=400)),
                ('image', models.URLField()),
                ('url', models.URLField()),
                ('yield', models.IntegerField()),
                ('calories', models.FloatField()),
                ('totalTime', models.IntegerField()),
                ('cuisineType', models.CharField(max_length=400)),
                ('mealType', models.CharField(max_length=400)),
                ('dishType', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
