# Generated by Django 2.2.10 on 2021-08-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='meals',
        ),
    ]
