# Generated by Django 2.2.10 on 2021-08-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('recipes', '0002_remove_recipe_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='meals.Meal', verbose_name='Recipes'),
        ),
    ]
